-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtxiIcVH/woNEP8+v
4vNE/Uk7RzlPfpQCHJ4BG9uYdQCgCgYIKoZIzj0DAQehRANCAASlS3/XL9HWvUFe
VT6f5J8ihAmNfPZb71XBiTito5S3hV6vC4dOBLNOgtOAV/41xDadrJgWGx0Mftnl
BDE+gXcX
-----END PRIVATE KEY-----