export default {
    GET_LOCATION_ID:"GET_LOCATION_ID",
    GET_PACKAGE_STATUS:"GET_PACKAGE_STATUS",
    GET_USER_ID:"GET_USER_ID",
    GET_USER_DATA: 'GET_USER_DATA',
    GET_BASE_PACKAGE:"GET_BASE_PACKAGE",
    GET_GRAPH_DATA:"GET_GRAPH_DATA",
    GET_KWH_DATA:"GET_KWH_DATA",
    GET_REMAINING_DATA:"GET_REMAINING_DATA",
    // week constants start
GET_WEEK_KWH:"GET_WEEK_KWH",
GET_WEEK_GRAPH_DATA:"GET_WEEK_GRAPH_DATA",
    // week constants end
};