export default {
  GET_LOCATION_ID: 'GET_LOCATION_ID',
  GET_PACKAGE_STATUS: 'GET_PACKAGE_STATUS',
  GET_USER_ID: 'GET_USER_ID',
  GET_EMAIL_DATA:"GET_EMAIL_DATA",
  GET_USER_DATA: 'GET_USER_DATA',
  GET_BASE_PACKAGE: 'GET_BASE_PACKAGE',

  GET_COMPLETE_DATA: 'GET_COMPLETE_DATA',
  GET_PLAN_PURCHAGE: 'GET_PLAN_PURCHAGE',

  GET_GRAPH_DATA: 'GET_GRAPH_DATA',
  GET_KWH_DATA: 'GET_KWH_DATA',
  GET_REMAINING_DATA: 'GET_REMAINING_DATA',
  // week constants start
  GET_WEEK_KWH: 'GET_WEEK_KWH',
  GET_WEEK_GRAPH_DATA: 'GET_WEEK_GRAPH_DATA',
  GET_MONTH_DATA: 'GET_MONTH_DATA',
  GET_QUARTER_DATA: 'GET_QUARTER_DATA',
  GET_YEAR_DATA: 'GET_YEAR_DATA',
  // week constants end

  //dashboard boxtwo and price details data start
  GET_BOX_TWO_DATA_DASHBOARD: 'GET_BOX_TWO_DATA',
  GET_PRICE_AND_DETAILS_DATA: 'GET_PRICE_AND_DETAILS_DATA',
  //dashboard boxtwo and price details data end
  CHARGER_STATUS: 'CHARGER_STATUS',
  DATA_FOR_PAYMENT: 'DATA_FOR_PAYMENT',
};
